--to import shp to psql
--shp2pgsql -I -s 4326 [SHAPEFILENAME].shp public.[TABLENAME] | psql -U [USERNAME] -h [HOSTNAME] -d [DATABASENAME]
CREATE TABLE sf_pop_bg_2010 (
    "geom" geometry,
    "STATEFP10" varchar(2),
    "COUNTYFP10" varchar(3),
    "TRACTCE10" varchar(6),
    "BLKGRPCE10" varchar(1),
    "geoid10" varchar(12),
    "NAMELSAD10" varchar(13),
    "MTFCC10" varchar(5),
    "FUNCSTAT10" varchar(1),
    "ALAND10" int8,
    "AWATER10" int8,
    "INTPTLAT10" varchar(11),
    "INTPTLON10" varchar(12),
    "join" int4,
    "geoid" int4,
    "total_population" int4
);

CREATE TABLE sf_muni_gtfs_shapes_line (
    "shape_id" int8,
    "line_geom" geometry
);

CREATE TABLE sf_muni_gtfs_stops (
    "geom" geometry,
    "stop_id" int4,
    "stop_code" int4,
    "stop_name" varchar,
    "stop_desc" varchar,
    "stop_lat" float8,
    "stop_lon" float8,
    "zone_id" varchar,
    "stop_url" varchar,
    PRIMARY KEY ("id")
);

CREATE TABLE sf_hospital (
    "geom" geometry,
    "hospital n" varchar(254),
    "address" varchar(254),
    "city" varchar(254),
    "state" varchar(254),
    "latitude" numeric,
    "longitude" numeric,
    "accuracy s" numeric,
    "accuracy t" varchar(254),
    "number" int8,
    "street" varchar(254),
    "unit type" varchar(254),
    "unit numbe" varchar(254),
    "city_1" varchar(254),
    "state_1" varchar(254),
    "county" varchar(254),
    "zip" int8,
    "country" varchar(254),
    "source" varchar(254),
    PRIMARY KEY ("id")
);

CREATE TABLE sf_restaurant (
    "geom" geometry,
    "location id" varchar,
    "business account number" int4,
    "ownership name" varchar,
    "dba name" varchar,
    "street address" varchar,
    "city" varchar,
    "state" varchar,
    "source zipcode" int4,
    "business start date" varchar,
    "business end date" varchar,
    "location start date" varchar,
    "location end date" varchar,
    "mail address" varchar,
    "mail city" varchar,
    "mail zipcode" varchar,
    "mail state" varchar,
    "naics code" varchar,
    "naics code description" varchar,
    "parking tax" varchar,
    "transient occupancy tax" varchar,
    "lic code" varchar,
    "lic code description" varchar,
    "supervisor district" int4,
    "neighborhoods - analysis boundaries" varchar,
    "business corridor" varchar,
    "business location" varchar,
    "sf find neighborhoods" int4,
    "current police districts" int4,
    "current supervisor districts" int4,
    "analysis neighborhoods" int4,
    "delete - zip codes" int4,
    "delete - fire prevention districts" int4,
    "delete - supervisor districts" int4,
    "delete - current police districts" int4,
    "delete - neighborhoods" int4,
    "delete - police districts" int4,
    "latitude" float8,
    "longitude" float8,
    "accuracy score" float8,
    "accuracy type" varchar,
    "number" int4,
    "street" varchar,
    "unit type" varchar,
    "unit number" varchar,
    "city_1" varchar,
    "state_1" varchar,
    "county" varchar,
    "zip" int4,
    "country" varchar,
    "source" varchar
);
